# Generated by Django 5.1.5 on 2025-02-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default=0, upload_to='gallery/'),
        ),
    ]
