# Generated by Django 5.1.5 on 2025-02-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='fl',
            field=models.FileField(default=0, upload_to='document/'),
        ),
    ]
